@startuml inline_umlgraph_1.png
class CSVParser {
-filename : std::string
+CSVParser(const std::string& filename)
+parse() : std::vector<Record>

}
@enduml
@startuml inline_umlgraph_3.png
class Record {
-AutoConsumption : double
-Consumption : double
-Export : double
-Import : double
-Production : double
+Record()
+getAutoConsumption() : double {query}

}
@enduml
